udpate workflow file

diff --git a/.github/workflows/export_markdown.yaml b/.github/workflows/export_markdown.yaml
--- a/.github/workflows/export_markdown.yaml
+++ b/.github/workflows/export_markdown.yaml
@@ -1,7 +1,7 @@
 name: Convert Markdown to PDF
 
 on:
-  workflow_dispatch:
+  workflow_dispatch:  # Allows manual triggering
   push:
   pull_request:
 
@@ -39,11 +39,16 @@ jobs:
           mkdir -p "$OUTPUT_DIR"
           echo "Current working directory:"
           pwd
+
           for INPUT_FILE in *.md; do
               if [ -f "$INPUT_FILE" ]; then
                   echo "Processing file: $INPUT_FILE"
                   OUTPUT_FILE="$OUTPUT_DIR/${INPUT_FILE%.md}.pdf"
                   mdpdf "$INPUT_FILE" -o "$OUTPUT_FILE"  # Use mdpdf for conversion
+                  if [ $? -ne 0 ]; then  # Check if mdpdf succeeded
+                      echo "Conversion failed for $INPUT_FILE"
+                      exit 1  # Exit if there's a conversion error
+                  fi
                   echo "Conversion of $INPUT_FILE completed. Output file: $OUTPUT_FILE"
               else
                   echo "No .md files to convert."
