test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -21,25 +21,24 @@ jobs:
           echo "${{ secrets.SP_ACCESS_TOKEN }}" > access_token.txt
           echo "Access token retrieved successfully."
 
-      - name: Download file from SharePoint
+      - name: Get file content from SharePoint
         run: |
-
-          DOWNLOAD_URL="https://graph.microsoft.com/v1.0/sites/055adf94-42e1-4941-8cd8-eb7ab60ca37d/drive/items/01HTWZYNWLWIF75TXITRAKXS72RFJ4NTTO/content"
-          echo "Download URL: $DOWNLOAD_URL"
-
-          FILE_NAME="README.md"
-          echo "Downloading file: $FILE_NAME"
-
-          response=$(curl -X GET \
-            -H "Authorization: Bearer $(cat access_token.txt)" \
-            -H "Accept: application/octet-stream" \
-            -w "%{http_code}" \
-            -o response.txt \
-            "$DOWNLOAD_URL")
-          
-          if [ "$response" -eq 200 ]; then
-            echo "File downloaded successfully and saved as ./$FILE_NAME."
-          else
-            echo "Failed to download file. HTTP status code: $response"
-            exit 1
-          fi
+            
+            DOWNLOAD_URL="https://graph.microsoft.com/v1.0/sites/055adf94-42e1-4941-8cd8-eb7ab60ca37d/drive/items/01HTWZYNWLWIF75TXITRAKXS72RFJ4NTTO/content"
+            echo "Download URL: $DOWNLOAD_URL"
+            
+            response=$(curl -L -v -X GET \
+              -H "Authorization: Bearer $(cat access_token.txt)" \
+              -H "Accept: application/octet-stream" \
+              -w "%{http_code}" \
+              -o response.txt \
+              "$DOWNLOAD_URL")
+            
+            if [ "$response" -eq 200 ]; then
+              echo "File content retrieved successfully."
+              echo "Response content:"
+              cat response.txt
+            else
+              echo "Failed to retrieve file content. HTTP status code: $response"
+              exit 1
+            fi
